[project]
name = "docfoge"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.139.2",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "pymupdf4llm>=1.28.0",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.51.0",
]
